# src/models/schemas.py
from __future__ import annotations
from typing import List, Optional, Any
from pydantic import BaseModel, Field
from enum import Enum

class OriginType(str, Enum):
    """Enumeration for the origin of the document."""
    NATIVE_PDF = "native_pdf"
    SCANNED_PDF = "scanned_pdf"
    IMAGE = "image"
    UNKNOWN = "unknown"

class LayoutComplexity(str, Enum):
    """Enumeration for the layout complexity of the document."""
    SIMPLE = "simple"
    MODERATE = "moderate"
    COMPLEX = "complex"

class DocumentProfile(BaseModel):
    """
    Metadata profile for a document, generated by the Triage Agent.
    This guides the Structure Extraction Layer.
    """
    document_id: str = Field(..., description="Unique identifier for the document.")
    origin_type: OriginType = Field(..., description="Whether the document is native, scanned, or an image.")
    layout_complexity: LayoutComplexity = Field(..., description="The estimated complexity of the document's layout.")
    language: str = Field(default="en", description="The primary language of the document (ISO 639-1 code).")
    domain_hint: Optional[str] = Field(None, description="A hint about the document's domain (e.g., 'financial_report', 'scientific_paper').")
    estimated_extraction_cost: float = Field(..., description="A cost estimate (e.g., in credits or a normalized unit) for processing.")

class BoundingBox(BaseModel):
    """
    Represents a rectangular region on a page.
    Coordinates are typically normalized to the page dimensions (e.g., 0.0 to 1.0).
    """
    x1: float
    y1: float
    x2: float
    y2: float
    page_number: int = Field(..., description="The page number where the box is located.")

class ProvenanceChain(BaseModel):
    """
    Tracks the origin of an extracted piece of information back to the source document.
    """
    document_id: str
    bounding_box: BoundingBox

class LDU(BaseModel):
    """
    A Logical Document Unit (LDU). This is a semantic chunk of content,
    which should not be broken up (e.g., a table row, a paragraph, a figure with its caption).
    """
    lfu_id: str = Field(..., description="Unique identifier for this logical unit.")
    ldu_type: str = Field(..., description="Type of the LDU (e.g., 'paragraph', 'table', 'header', 'caption').")
    content: Any = Field(..., description="The extracted content (e.g., text, or structured data for a table).")
    provenance: ProvenanceChain = Field(..., description="The provenance chain for this LDU.")
    embedding: Optional[List[float]] = Field(None, description="Vector embedding for this LDU.")

class PageIndex(BaseModel):
    """
    A hierarchical index of the document's structure, like a smart table of contents.
    This is a recursive model to represent the tree structure.
    """
    node_id: str
    title: str = Field(..., description="LLM-generated title for this section.")
    summary: str = Field(..., description="LLM-generated summary for this section.")
    ldu_ids: List[str] = Field(default_factory=list, description="List of LDU IDs belonging to this section.")
    children: List[PageIndex] = Field(default_factory=list, description="Sub-sections of this index node.")
    provenance: ProvenanceChain

class ExtractedDocument(BaseModel):
    """
    The final, fully processed representation of a document.
    """
    document_id: str
    profile: DocumentProfile
    ldus: List[LDU]
    page_index: PageIndex
